### ISSUE TITLE
Kotlin Support Tracker

### ISSUE THREAD

**Issue by kageiit** [uber/okbuck#400]
- [x] Pure kotlin modules
- [x] Mixed kotlin/java modules
- [x] Android Kotlin modules
- [x] Kapt
- [x] Kotlin rule support for `buck project` https://github.com/facebook/buck/pull/1200

**Comment by runningcode** [comment]
We've been slacking on keeping these github issues up to date.

Buck itself supports pure kotlin modules, mixed kotlin/java modules and android kotlin modules.
Buck is missing support for [kapt](https://github.com/facebook/buck/issues/956) and [robolectric_rule](https://github.com/facebook/buck/issues/1349). We should add robolectric_rule support to this list.

Also, okbuck support for mixed kotlin/java and android kotlin modules is on this branch: https://github.com/runningcode/okbuck/tree/no/kotlin-android-mixed.
They won't be upstreamed because @kageiit is planning on adding support in a large refactor of okbuck.

**Comment by kageiit** [comment]
[Okbuck v0.22.0](https://github.com/uber/okbuck/releases/tag/v0.22.0) is out with Kotlin Android support and mixed Kotlin/Java modules support

**Comment by kageiit** [comment]
@runningcode I already added `robolectric_test` support to okbuck. As soon as buck starts supporting it, it should start working out of the box

**Comment by artem-zinnatullin** [comment]
What is the state of `kapt` support? Thanks!

**Comment by kageiit** [comment]
It is blocked by https://github.com/facebook/buck/issues/956

**Comment by talenguyen** [comment]
What about the status of this. I saw kotlin is supported in the [Features](https://github.com/uber/okbuck/wiki/Features) page.

**Comment by kageiit** [comment]
Yes everything is supported except `kapt`. @cwoodwar6 is currently working on kapt support

**Comment by erawhctim** [comment]
Forgive my ignorance, but what does partial kotlin support entail exactly? What does the current "partial" kotlin support (e.g. everything but `kapt`) get us? Can you build everything but annotation-processor-based things?

**Comment by kageiit** [comment]
> Forgive my ignorance, but what does partial kotlin support entail exactly? What does the current "partial" kotlin support (e.g. everything but kapt) get us? Can you build everything but annotation-processor-based things?

Yes. If your gradle modules do not use the `kapt` configuration for annotation processors, they should work fine.

**Comment by kassim** [comment]
It's looking hopeful https://github.com/cwoodwar6/buck/pull/3

**Comment by aphexcx** [comment]
Go go go! 🤞  Our app is majority Kotlin by now and I'm dying to give okbuck another shot (our gradle build times are 4-5 minutes).

**Comment by BharathMG** [comment]
Looks like https://github.com/facebook/buck/issues/956 just got closed!

**Comment by lenguyenthanh** [comment]
Can't wait seeing this issue got closed too.
